# PATHS
# Python 3
PATH="/usr/local/Cellar/python3/3.6.2/bin:${PATH}"
export PATH

##GIT EDITOR
export GIT_EDITOR="/usr/local/Cellar/neovim/0.2.0_1/bin/nvim"

## fix encoding python
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Workon
export WORKON_HOME=$HOME/.envs
export PIP_VIRTUALENV_BASE=$WORKON_HOME

# makes pip detect an active virtualenv and install to it
export PIP_RESPECT_VIRTUALENV=true
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
