[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color
if [ -z "$TMUX" ]
then
	    tmux 
fi
if command -v pyenv 1>/dev/null 2>&1;
then
	eval "$(pyenv init -)"
fi
#
# User configuration sourced by interactive shells
#

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh;

source ~/.aliases
fortune pythonzen | lolcat
